version: 0.2

env:
    variables:
         S3_BUCKET: "{{S3_BUCKET}}"

phases:
  pre_build:
    commands:
        - echo Checking the path...
        - pwd
        - echo Installing source NPM dependencies...
        - cd shell
        - npm install
        
  build:
    commands:
        - echo Build started
        - curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -
        - sudo yum install -y nodejs
        - node --version
        - npm run build

  post_build:
    commands:
        - echo dist path
        - cd dist/shell
        
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes